# Generated by Django 3.1.4 on 2020-12-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gropagorskaprzodownika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'GropaGorskaPrzodownika',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupagorska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(db_column='Nazwa', max_length=255)),
            ],
            options={
                'db_table': 'GrupaGorska',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Odznaka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(db_column='Nazwa', max_length=255)),
                ('stopien', models.CharField(db_column='Stopien', max_length=255)),
                ('wymaganaliczbapunktow', models.IntegerField(db_column='WymaganaLiczbaPunktow')),
                ('minimalnywymaganywiek', models.IntegerField(blank=True, db_column='MinimalnyWymaganyWiek', null=True)),
                ('maksymalnywymaganywiek', models.IntegerField(blank=True, db_column='MaksymalnyWymaganyWiek', null=True)),
                ('innewymagania', models.CharField(blank=True, db_column='InneWymagania', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Odznaka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Odznakaturysty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datazdobycia', models.TextField(blank=True, db_column='DataZdobycia', null=True)),
            ],
            options={
                'db_table': 'OdznakaTurysty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Polaczenie',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('punktyz', models.IntegerField(blank=True, db_column='PunktyZ', null=True)),
                ('punktydo', models.IntegerField(blank=True, db_column='PunktyDo', null=True)),
                ('nazwa', models.CharField(blank=True, db_column='Nazwa', max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'Polaczenie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Polaczenietrasy',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('czypowrotne', models.IntegerField(db_column='CzyPowrotne')),
                ('kolejnosc', models.IntegerField(db_column='Kolejnosc')),
            ],
            options={
                'db_table': 'PolaczenieTrasy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Potwierdzenieprzebyciatrasy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czyprzodownikuczestniczyl', models.IntegerField(db_column='CzyPrzodownikUczestniczyl')),
            ],
            options={
                'db_table': 'PotwierdzeniePrzebyciaTrasy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Punktpolaczenia',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('kolejnosc', models.IntegerField(db_column='Kolejnosc')),
            ],
            options={
                'db_table': 'PunktPolaczenia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Punkttrasy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(db_column='Nazwa', max_length=255)),
            ],
            options={
                'db_table': 'PunktTrasy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(db_column='Nazwa', max_length=255)),
            ],
            options={
                'db_table': 'Rola',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trasa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('datarozpoczecia', models.TextField(blank=True, db_column='DataRozpoczecia', null=True)),
                ('datazakonczenia', models.TextField(blank=True, db_column='DataZakonczenia', null=True)),
                ('nazwa', models.CharField(db_column='Nazwa', max_length=255)),
                ('jestplanowana', models.IntegerField(db_column='JestPlanowana')),
                ('jestodbywana', models.IntegerField(db_column='JestOdbywana')),
            ],
            options={
                'db_table': 'Trasa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(db_column='Login', max_length=255)),
                ('jestniepelnosprawny', models.IntegerField(blank=True, db_column='JestNiepelnosprawny', null=True)),
                ('dataurodzenia', models.TextField(blank=True, db_column='DataUrodzenia', null=True)),
                ('imie', models.CharField(db_column='Imie', max_length=255)),
                ('nazwisko', models.CharField(db_column='Nazwisko', max_length=255)),
                ('numerlegitymacji', models.CharField(blank=True, db_column='NumerLegitymacji', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Uzytkownik',
                'managed': False,
            },
        ),
    ]
