# Generated by Django 3.1.4 on 2021-01-13 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasa',
            name='odznakaturysty',
            field=models.ForeignKey(blank=True, db_column='OdznakaTurysty', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.odznakaturysty'),
        ),
    ]
