# Generated by Django 3.1.4 on 2021-01-13 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trasa_odznakaturysty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polaczenietrasy',
            name='polaczenieid',
            field=models.ForeignKey(db_column='PolaczenieID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='polaczeniatrasy', to='core.polaczenie'),
        ),
    ]
